### ISSUE TITLE
Default narrow options redundancy

### ISSUE THREAD

**Issue by gitrj95** [liuyinz/consult-todo#4]
Hi, I've noticed that both FIXME and BUG are categories in the narrowing. To me, FIXME implies a known bug that needs to be fixed, so BUG is redundant. I think having a DEBUG label, for which a problem is suspected but not identified, is more useful.

**Comment by liuyinz** [comment]
it's totally customized by yourself.

**Comment by gitrj95** [comment]
I don't think I explained myself well. The interface of having both FIXME and BUG is redundant. Can you explain the labels?
