### ISSUE TITLE
Wrap grep-command internally, expose own grep-command, or stop overwriting it?

### ISSUE THREAD

**Issue by DivineDominion** [liuyinz/consult-todo#5]
https://github.com/liuyinz/consult-todo/blob/84f3c9876a285f733d75053076a97cc30f7d8eb9/consult-todo.el#L266-L267

These lines make using `rg` or `ag` or whatever faster `grep` alternative you have installed harder.

Compatibility with grep settings would be great, like explained here for `rg`: https://stegosaurusdormant.com/emacs-ripgrep/

**Comment by liuyinz** [comment]
Command `consult-todo-dir` is not recommended to use for users because of existing issues.

**Comment by DivineDominion** [comment]
Oh, which issue are you referring to?
