### ISSUE TITLE
consult-todo-narrow automatically from hl-todo-keyword-faces

### ISSUE THREAD

**Issue by sejgit** [liuyinz/consult-todo#6]
Love the package!
(I know you know but the directory & project commands have a tonne of potential.  Works in my denote directories but not well for Project)

In my config I added a little routine to take hl-todo-keyword-faces and turn it into the consult-todo-narrow complete with first chars. As long as there are no repeating first letters it works slick.  I sort them for readability.
You may want to make this a "feature".
Keep it up!!

(setq consult-todo-narrow
		(let (value)
		  (dolist (element (sort hl-todo-keyword-faces :reverse t) value)
			(setq value (cons
						 (cons (string-to-char 
                                                    (downcase (substring (car element) 0 1)))
						  (car element))
						 value)))))

**Comment by liuyinz** [comment]
Maybe add it to README is a good choice.

**Comment by sejgit** [comment]
Ya, likely a good choice in current state. If I get some time I could add a fallback for repeats. Progress from lowercase to uppercase to control-lower to meta lower, etc. Something like that or at least a warning that the first one is chosen if duplicate exists. For now...readme.
